sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.5
git:
  submodules: true
branches:
  only:
  - keras-2.0
before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get -y install curl octave liboctave-dev
  - octave --eval "pkg install -forge -verbose io"
  - octave --eval "pkg install -forge -verbose statistics"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test tests
